import {
	jaccArticleStrategy,
	jaccImagingArticleStrategy,
	jaccHeartFailureArticleStrategy,
	jaccEpArticleStrategy,
	jaccCardioOncoArticleStrategy,
	jaccInterventionsArticleStrategy,
	jaccAdvancesArticleStrategy,
	jaccAsiaArticleStrategy,
	jaccBasicTranslationalArticleStrategy,
	ehjArticleStrategy,
	rsnaArticleStrategy,
	rsnaReviewArticleStrategy,
	ehjCardioImagingArticleStrategy,
	ehjDigitalHealthArticleStrategy,
	ahaCirculationArticleStrategy,
	ahaCirculationImagingArticleStrategy,
	ahaHypertensionArticleStrategy,
	nejmArticleStrategy,
	jcmrArticleStrategy,
	jmriArticleStrategy,
	acvdArticleStrategy,
	lancetArticleStrategy,
	ahaCirculationResearchArticleStrategy,
} from '../journals';
import { Source } from '../../types/types';

const articleStrategies = {
	JACC: jaccArticleStrategy,
	JACCImaging: jaccImagingArticleStrategy,
	JACCHeartFailure: jaccHeartFailureArticleStrategy,
	JACCEP: jaccEpArticleStrategy,
	JACCardioOnco: jaccCardioOncoArticleStrategy,
	JACCInterventions: jaccInterventionsArticleStrategy,
	JACCAdvances: jaccAdvancesArticleStrategy,
	JACCAsia: jaccAsiaArticleStrategy,
	JACCBasicTranslational: jaccBasicTranslationalArticleStrategy,
	RSNA: rsnaArticleStrategy,
	RSNAReview: rsnaReviewArticleStrategy,
	EHJ: ehjArticleStrategy,
	EHJCardioImaging: ehjCardioImagingArticleStrategy,
	EHJDigitalHealth: ehjDigitalHealthArticleStrategy,
	AHACirculation: ahaCirculationArticleStrategy,
	AHACirculationImaging: ahaCirculationImagingArticleStrategy,
	AHAHypertension: ahaHypertensionArticleStrategy,
	NEJM: nejmArticleStrategy,
	JCMR: jcmrArticleStrategy,
	JMRI: jmriArticleStrategy,
	ACVD: acvdArticleStrategy,
	LANCET: lancetArticleStrategy,
	AHACirculationResearch: ahaCirculationResearchArticleStrategy,
};

export const getArticleStrategy = (source: Source) => articleStrategies[source];
